name: autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  ftrackertest:
    runs-on: ubuntu-latest
    container: golang:1.21

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkout tests code
        uses: actions/checkout@v4
        with:
          repository: 'fox_meller/go-autotests1'
          path: '.autotests'

      - name: Gather files
        run: |
          cp .autotests/cmd/fitnesstest/main_test.go main_test.go

      - name: Run tests
        run: |
          go mod tidy
          go test -test.v ./...
